baseurl: ''
url: 'https://naturalonelife.com'
name: 'Natural One Life'
author: Alejandro Argote - Natural One Life
instagram: https://www.instagram.com
facebook: https://www.facebook.com
maps: https://maps.app.goo.gl/XCsyKqaQ5pQTx1g47
telefono: 3123278881

markdown: kramdown

permalink: :slug

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []
