baseurl: ''
url: 'https://clientefiel.com.co'
name: 'revisemos.com'
author: Alejandro Argote - Natural One Life
instagram: https://www.instagram.com/naturalonel/
facebook: https://www.facebook.com/profile.php?id=61565457025504
maps: https://maps.app.goo.gl/XCsyKqaQ5pQTx1g47
telefono: 3123278881

markdown: kramdown

permalink: :slug

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []
